services:
  - type: web
    name: foundation-erp
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false
